### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by shrutishankar28** [danomatic/react-pdf-html#1]
Can you please provide the working code of an example?

**Comment by danomatic** [comment]
I've updated the README. Do you have any questions about it?
https://github.com/danomatic/react-pdf-html/blob/main/README.md#usage

**Comment by shrutishankar28** [comment]
> I've updated the README. Do you have any questions about it?
> https://github.com/danomatic/react-pdf-html/blob/main/README.md#usage

No questions, thank you!  :)
