### ISSUE TITLE
Problem with text formatting

### ISSUE THREAD

**Issue by yurtsiv** [danomatic/react-pdf-html#10]
Hi, I'm having trouble properly rendering nested tags.

The following code:

```javascript
const html = `<html>
  <style>
    html {
      fontFamily: Rubik;
    }
  </style>

  <body>
    <p>
        Paragraph with <strong>bold</strong>, <i>italic</i>, <u>underline</u>,
        <s>strikethrough</s>,
        <strong><i>italic strong</i><strong>,
        <strong><u><s><i>and all of the above</i></s></u></strong>
    </p>
  </body>
</html>`;

function Pdf() {
  return (
    <Document>
      <Page>
        <Html>{html}</Html>;
      </Page>
    </Document>
  );
}
```

produces this

![Screenshot from 2021-08-30 18-39-24](https://user-images.githubusercontent.com/18295488/131365808-706e9944-7301-40f7-a91d-70969792d9fb.png)

As you can see, "italic strong" is in fact only italic, and for "and all of the above" only italic & strikethrough is applied.

This is how fonts are registered:

```javascript
[
  {
    family: 'Rubik',
    src: '/fonts/rubik/Rubik-Regular.ttf',
  },
  {
    family: 'Rubik',
    src: '/fonts/rubik/Rubik-Italic.ttf',
    fontStyle: 'italic',
  },
  {
    family: 'Rubik',
    src: '/fonts/rubik/Rubik-Bold.ttf',
    fontWeight: 'bold',
  },
].forEach(font => {
   Font.register(font);
})
```

Seems like cascading styles should be supported due to the fact that you provided such an example in the README, so probably I'm doing something wrong. Any help would be appreciated.

P.S. I was trying to make a small reproduction on [codesandbox.io](https://codesandbox.io/) but couldn't get `react-pdf` to work there. Let me know, if you really need a reproduction, I'll try something else.

**Comment by mikey0000** [comment]
@yurtsiv PDF rendering doesn't cascade styles, this probably would require a huge amount of effort, you'll just have to style that element specifically. Yes there is a base stylesheet but it is by no means comprehensive.

in terms of repl, use https://react-pdf.org/repl

**Comment by danomatic** [comment]
@yurtsiv and @mikey0000  `react-pdf-html` actually does cascade styles the best that it can, but I've noticed that combining  things like italic and bold doesn't work in `react-pdf`, HTML abstraction aside. I think this would be a bug/feature request for that project. If either of you think that I'm misunderstanding something here, please let me know and we can reopen this.

**Comment by yurtsiv** [comment]
@danomatic @mikey0000 I finally discovered the reason why **_bold italic_** doesn't work. You need to register a font that is both **bold** and _italic_ like this

```javascript
Font.register({
   name: 'Rubik',
   src: '/fonts/rubik/Rubik-BoldItalic.ttf',
   fontStyle: 'italic',
   fontWeight: 'bold'
})
```

What doesn't seem to work is merging values of the same property, f.e. the following HTML

```html
<u><s>underline strikethrough</s></u>
```

probably (didn't verify that) results in the following JSX

```html
<Text style={{ textDecoration: 'line-through' }}>
  underline strikethrough
</Text>
```

but should be

```html
<Text style={{ textDecoration: 'underline line-through' }}>
   underline strikethrough
</Text>
```

So it seems to be a problem with `react-pdf-html` after all.

**Comment by danomatic** [comment]
@yurtsiv good catch. `react-pdf-html` doesn't actually collapse style entries because `react-pdf` actually supports arrays of styles, like so:

```
<Text style={[{ textDecoration: 'underline' }, { textDecoration: 'line-through' }]}>underline AND strikethrough</Text>
```

Also, in the case with nested tags, the JSX generated by `react-pdf-html` is more likely something like this:
```

<Text style={{ textDecoration: 'underline' }}>
  <Text style={{ textDecoration: 'line-through' }}>
    underline AND strikethrough
  </Text>
</Text>
```

In both cases, `react-pdf` internally merges/collapses the styles when it renders the text, but for textDecoration is seems to just overwrite the inherited style rather than combining the values.  Try pasting this in the `react-pdf` repl (https://react-pdf.org/repl) and you'll see what I mean:

```
      <Text style={{ textDecoration: 'underline line-through' }}>underline AND strikethrough</Text>
      <Text style={[{ textDecoration: 'underline' }, { textDecoration: 'line-through' }]}>underline AND strikethrough</Text>
      <Text style={{ textDecoration: 'underline' }}>
        <Text style={{ textDecoration: 'line-through' }}>
          underline AND strikethrough
        </Text>
      </Text>
```

**Comment by danomatic** [comment]
@yurtsiv I just filed a bug with `react-pdf`:

https://github.com/diegomura/react-pdf/issues/1489

**Comment by yurtsiv** [comment]
@danomatic Cool, thanks!

**Comment by danomatic** [comment]
@yurtsiv the bug is fixed in an open PR:

https://github.com/diegomura/react-pdf/issues/1489#issuecomment-915071275
