### ISSUE TITLE
Html Span tag is not supporting

### ISSUE THREAD

**Issue by SergiiMarkin** [danomatic/react-pdf-html#14]
Here is my code snippet.

<Document>
          <Page>
              <Html>
                  <div style="padding: 8px">
                     <p><span>www.w3school.com</span><br>
                  </div>
              </Html>
          </Page>
 </Document>
      
      This is not rendering, just empty screen.
      Can you please check it now?
      
      Thanks in advance!

**Comment by SergiiMarkin** [comment]
![image](https://user-images.githubusercontent.com/85687049/135634111-b6b3a71a-b887-4892-aeec-be4630e6deb0.png)
Some tags like <span />, <figure /> are not rendering.
So all the contents inside span, figure tags are not displaying, just empty screen.

Cheers!

**Comment by danomatic** [comment]
Does it work if you wrap it in a `<div>` tag or if you wrap the `<Html>` component in a `<View>` component?

**Comment by SergiiMarkin** [comment]
Thanks for your reply.
The span is rendering by wrapping with View.
But figure is still not rendering.

Thanks for your suppport!

**Comment by danomatic** [comment]
Yeah that doesn't seem right. What if you try `<div>'<span>sdfsdfsdf</span></div>'`? I'm thinking there is something wrong with not having a block element around it.

**Comment by danomatic** [comment]
@SergiiMarkin this is fixed in the latest version! `<span>` tags weren't rendering at all. sorry about that!

**Comment by guillecardozo** [comment]
Hello, I have the same problem. the span tag is not rendering on my github page. any idea?

**Comment by danomatic** [comment]
> Hello, I have the same problem. the span tag is not rendering on my github page. any idea?

Are you using the latest version?
