### ISSUE TITLE
External css can import ?

### ISSUE THREAD

**Issue by SergiiMarkin** [danomatic/react-pdf-html#15]
There are css styles to write inside style tag.
`const html = `<html>
  <body>
    <style>
      A lot of css styles.....
    </style>`

So I need to import css files.

Is this possible to import like below?
`const html = <html>
                         <link rel="stylesheet" href="./assets/ckeditor.css" type="text/css">
                       </html>
<Document>
          <Page>
              <Html>
                  {html}
              </Html>
          </Page>
      </Document>`

Thanks in advance!

**Comment by danomatic** [comment]
That's a great idea and should be possible.

**Comment by lala3344** [comment]
after adding link getting this warning (Excluding "link" because it has no renderer) and styling also not applied
Please provide how to use external styling

**Comment by danomatic** [comment]
@lala3344 this feature is not yet supported

**Comment by danomatic** [comment]
@lala3344 @SergiiMarkin I just implemented a version of this, released in `v1.2.0`
