### ISSUE TITLE
Error: Failed to set an indexed property on 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by Leksat** [danomatic/react-pdf-html#17]
The error appears if HTML contains links.

When rendering with `PDFViewer`, the error isn't visible.

Full error:
```
Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported.
```

Sandbox: https://codesandbox.io/s/elegant-tu-6s7uh?file=/src/App.js

It looks like the link's `style` is an array, but it should be an object.

**Comment by Leksat** [comment]
Hmm... It looks like `@react-pdf/renderer` just does not support rendering PDFs in HTML (without `PDFViewer` wrapper). So closing this issue.

But I wonder how https://v1.react-pdf.org/repl does it 🤔

**Comment by Leksat** [comment]
Ah! Repl generates PDF, gets it as a blob url, and passes to [`react-pdf`](https://www.npmjs.com/package/react-pdf) which renders it on the page.

**Comment by steviecs** [comment]
@Leksat 

> Ah! Repl generates PDF, gets it as a blob url, and passes to [`react-pdf`](https://www.npmjs.com/package/react-pdf) which renders it on the page.

@Leksat it's been a long while since you made this observation. I'm needing to do exactly this for a feature I'm building, but am not quite clear on how to implement what you're describing.

If you recall this all, would you be able to shed some more light on it (or even provide a pseudocode sample)?

**Comment by Leksat** [comment]
@steviecs Unfortunately I don't have my code around. I tried make it work but could not: https://codesandbox.io/s/festive-babbage-qdpr85?file=/src/App.js
