### ISSUE TITLE
Doesn't it take into account the default styles in html code, like bootstrap classes or default styles like width, height etc.

### ISSUE THREAD

**Issue by agarwalishan** [danomatic/react-pdf-html#2]

**Comment by danomatic** [comment]
Not yet (I just started on this this week and I'm still getting the core pieces dialed in how I want). The html parse just parses the tags, text and attributes, but that could be done. This would require reading inline `style` attributes and parsing them with a CSS string parser, then applying the values as styles.

From there it could be extended to read style tags as long as the selectors can be applied.

**Comment by danomatic** [comment]
@agarwalishan I might have misread your question. it does apply default "browser" styles by doing a best match of default styles for all the common tags. I also just added support for inline `style` attributes. I think that answers your question so I'm going to mark this as resolved, but please let me know if there's something else you have in mind.
