### ISSUE TITLE
Failing to render a break inside a bold text

### ISSUE THREAD

**Issue by brunotalhate** [danomatic/react-pdf-html#21]
Rendering a line break inside of a bold text paragraph is returning the error `TypeError: Cannot read properties of undefined (reading 'height')`

```javascript
import Html from 'react-pdf-html'

export function TestComponent() {
  return (
    <Html>
      {
        '<body><div>regular text <strong>bold text<br />bold text</strong> regular text</p></div></body>'
      }
    </Html>
  )
}
```

It works as expected if the line break is added outside of the `strong` element.

Is there anything I can do to achieve it?

Thank you!

**Comment by danomatic** [comment]
I think this is from it being a block element inside an inline element. This is a bug and should be solvable.

**Comment by danomatic** [comment]
I believe this is fixed. Please try again with the latest version `1.1.5`

**Comment by brunotalhate** [comment]
Thank you for fixing it @danomatic. It's working like a charm!
