### ISSUE TITLE
Nested ordered lists share a single increment counter

### ISSUE THREAD

**Issue by toddpalino** [danomatic/react-pdf-html#23]
It looks like a set of nested ol tags will share a single counter (see attached image)

![Screen Shot 2021-11-24 at 12 41 28 PM](https://user-images.githubusercontent.com/1283289/143289182-219ac652-7db0-4cc8-9c9b-99202f5749f0.png)

The expected behavior would be that a new counter is used for each indent level (with deeper counters resetting correctly). Something like this:

1. This is one
    a. This is "a"
    b. This is "b"
    c. This is "c"
2. This is two
3. This is three
    a. This is also "a"
    b. This is also "b"

**Comment by danomatic** [comment]
Can you provide an example of the HTML you are having this issue with?

**Comment by toddpalino** [comment]
Now that I've pulled the HTML that was being generated (it's coming out of the QuillJS editor), this isn't a problem with the rendering at all:

```
<p>This is a numbered list:</p><ol><li>One</li><li class=\"ql-indent-1\">A</li><li class=\"ql-indent-1\">B</li><li class=\"ql-indent-1\">C</li><li>Two</li><li>Three</li></ol><p><br></p>```

What Quill is creating as a nested list isn't really nested at all. They're using CSS to assign different counts to the nesting levels using classes, rather than nesting another `ol` inside. So the display looks correct within the editor. And if you utilize the Quill classes for a read-only display (which is how my view page works), it looks correct as well. But trying to move this into a system like PDF that lacks full CSS support will produce a bad result.

**Comment by danomatic** [comment]
Ah, good to know. We could try adding support for whatever the CSS is. Is it using things like `:before`?

**Comment by toddpalino** [comment]
Yes. Here's a snip from their CSS:

```
.ql-editor ol li {
  counter-reset: list-1 list-2 list-3 list-4 list-5 list-6 list-7 list-8 list-9;
  counter-increment: list-0;
}
.ql-editor ol li:before {
  content: counter(list-0, decimal) '. ';
}
.ql-editor ol li.ql-indent-1 {
  counter-increment: list-1;
}
.ql-editor ol li.ql-indent-1:before {
  content: counter(list-1, lower-alpha) '. ';
}
.ql-editor ol li.ql-indent-1 {
  counter-reset: list-2 list-3 list-4 list-5 list-6 list-7 list-8 list-9;
}
.ql-editor ol li.ql-indent-2 {
  counter-increment: list-2;
}
.ql-editor ol li.ql-indent-2:before {
  content: counter(list-2, lower-roman) '. ';
}
.ql-editor ol li.ql-indent-2 {
  counter-reset: list-3 list-4 list-5 list-6 list-7 list-8 list-9;
}
```

**Comment by McleanWorkshield** [comment]
Facing the same issue here user inputed content from a react quill editor. Any progress or pointers here to assist? 

Is it possible to maybe import the stylesheet provided by React Quill into this HTML PDF Component?
