### ISSUE TITLE
How to render line breaks?

### ISSUE THREAD

**Issue by Unforgiven-wanda** [danomatic/react-pdf-html#25]
Hello, and thank you for this project.
I am trying to render some HTML from a rich text component (react-quill). However, all HTML that goes through your lib becomes inline, line breaks are completely ignored and this gives a result of text and lists all sitting on the same line.
Is it possible to force your interpreter to render line breaks as they would normally be in unstyled html?
Other than that, I have tried styling the elements with display: 'block', to no avail.
Thank you very much for your time!

**Comment by danomatic** [comment]
By default, browsers collapse whitespace into a single space. If you would like to disable this behavior, try `<Html collapse={false}></Html>` and let me know if that helps

**Comment by Unforgiven-wanda** [comment]
Hello again, and thank you for taking the time.
Adding `collapse={false}` did nothing unfortunately, this is the result for `const html = "<p>Text</p><ul><li>listitem1</li><li>listitem2</li></ul>";`
![Screenshot 2021-11-25 080544](https://user-images.githubusercontent.com/4499783/143395369-c141eef7-7bfd-4a23-aaeb-8053dd7c56ec.png)

When adding a `<br/>` tag like this `const html = "<p>Text</p><br/><ul><li>listitem1</li><li>listitem2</li></ul>";`
, I instead get this:
![Screenshot 2021-11-25 080744](https://user-images.githubusercontent.com/4499783/143395512-01b83fa0-cade-4912-9564-ba9b0356a13b.png)

Anything at this point helps.
Thanks!

**Comment by danomatic** [comment]
When I add that HTML snippet it renders as expected for me:

```jsx
    <Page size="LETTER">
      <Html>
        {`<p>Text</p><ul><li>listitem1</li><li>listitem2</li></ul>`}
      </Html>
    </Page>
```
<img width="1010" alt="Screen Shot 2021-11-30 at 10 54 49 AM" src="https://user-images.githubusercontent.com/459337/144109901-7e6ad98d-72b8-45ba-a24e-c5a03e433eae.png">

Perhaps you have an older version of one of the dependencies or some kind of style conflict. Let me know if you can determine why it's behaving differently for you.

**Comment by danomatic** [comment]
Perhaps you have `flexDirection: 'row'` for a parent element?

**Comment by danomatic** [comment]
Closing for now but let me know if there's more that I can help with.
