### ISSUE TITLE
Images become very small and cannot set height and width dynamically

### ISSUE THREAD

**Issue by omerfkati** [danomatic/react-pdf-html#28]
Hi I might be doing something wrong, but I would like for the images to have a max width and a height of auto

Images are always very small, and only adding width does not make them any longer.

![image](https://user-images.githubusercontent.com/93536415/154489882-febaead8-c608-4e17-b234-4af003daf67d.png)
(width set to 350 and height empty)

If I add both width and height it does work, but this is not ideal since in my use case images will be in different ratios.

This is what I would expect to work:
```
   img: {
            width: 350,
            height: "auto",
            margin: 0,
            padding: 0,

        }

```

However, this crashes the renderer.
Is this a bug, or am I doing something wrong?
Why are images not stretching to their original size?

I use the react-quill editor to add images and want to display this in a PDF. They are saved as base64 images.

**Comment by tonysobreira** [comment]
I'm having the same problem.
But i can't make images bigger even if i change both width and height.
I don't know if i'm doing something wrong;

```
const element = (
    <html>
      <body>
        <style>
          {`
          img: {
            width: 350,
            height: 350,
            margin: 0,
            padding: 0
          }
          `}
        </style>
        <img src="https://image.shutterstock.com/image-photo/tiny-floating-house-on-lake-600w-1980476267.jpg" />
      </body>
    </html>
  );

  const html2 = ReactDOMServer.renderToStaticMarkup(element);

  const html = `<img width="2000" height="2000" src="https://image.shutterstock.com/image-photo/tiny-floating-house-on-lake-600w-1980476267.jpg" />`;

  return (
    <PDFViewer style={{ width: window.innerWidth, height: window.innerHeight }}>
      <Document>
        <Page size='A4'>
          <Html>{html}</Html>
          <Html>{html2}</Html>
        </Page>
      </Document>
    </PDFViewer>
  )
}
```

![image](https://user-images.githubusercontent.com/12221017/154563693-e4d29a5b-7e5f-4bfc-8948-d27216dd9668.png)

**Comment by danomatic** [comment]
These props all pass through to react-pdf au I **think** you will have to take that up with them. But me know if you think something needs to be done in this library.

**Comment by tonysobreira** [comment]
I noticed that when i increase the font size the image grows as well, maybe some div is defining the size for everything, when everything is compiled.

![image](https://user-images.githubusercontent.com/12221017/154694930-b3cbb69e-65d9-407d-9c6a-65278ed3daba.png)

```
<Html style={{fontSize: '50px'}}>{relint.apresentacao}</Html>
<Html style={{fontSize: '100px'}}>{relint.apresentacao}</Html>
<Html style={{fontSize: '150px'}}>{relint.apresentacao}</Html>
```

Maybe this could help you find a solution?
@danomatic

**Comment by EHF32** [comment]
I'm having the same problem, any workaround?

**Comment by tonysobreira** [comment]
You can do this:

```
const stylesheet = {
      img: {
          width: 300,
          height: 150
      },
  };

<Html stylesheet={stylesheet}>{html}</Html>
```

The problem is that all images will have the same width and height.

**Comment by danomatic** [comment]
It seems to be an issue with the flex layout of the container. We will have to dig into the implementation to understand how this is occurring. Any assistance is welcome as I am very busy ATM.

**Comment by mahamedh** [comment]
I am facing same issue any update on this issue please any one @danomatic @tonysobreira @omerfkati

**Comment by danomatic** [comment]
@omerfkati, @tonysobreira, @EHF32 and @mahamedh I think this was caused by `react-pdf-html` wrapping some `Image`s in `Text`. The latest version `v1.1.12` should resolve this.

**Comment by cayman1066** [comment]
Well, @danomatic, I've got to be the luckiest SOB in the world today.  I **just** started using your library about 2 hours ago and was running up against the same image sizing problem.  I'd implemented @tonysobreira solution as a stop-gap measure.  Then, low and behold, you released a fix!  Which works wonderfully, by the way!  Maybe I should by a lottery ticket today! ;-)

Cheers, Mate!

**Comment by danomatic** [comment]
> Well, @danomatic, I've got to be the luckiest SOB in the world today. I **just** started using your library about 2 hours ago and was running up against the same image sizing problem. I'd implemented @tonysobreira solution as a stop-gap measure. Then, low and behold, you released a fix! Which works perfectly, by the way. Maybe I should by a lottery ticket today! ;-)
> 
> Cheers, Mate!

@cayman1066 I'm glad it made a difference! Thanks for dropping an encouraging note into the thread
