### ISSUE TITLE
Code blocks are not supported

### ISSUE THREAD

**Issue by edwindwalker** [danomatic/react-pdf-html#31]
I am using [remarkable](https://github.com/jonschlinkert/remarkable) in conjunction with this library to render markdown in a PDF. 

Typically, an HTML code block is achieved like so:
```html
<pre>
  <code class="language-ruby">
    def sum_eq_n?(arr, n)
      return true if arr.empty? && n == 0
      arr.product(arr).reject { |a,b| a == b }.any? { |a,b| a + b == n }
    end
  </code>
</pre>
```
(Specifically, this is how remarkable handles code blocks, see https://github.com/jonschlinkert/remarkable/blob/58b6945f203ca7a0bb5a0785df90a3a6a8b9e59c/lib/rules.js#L70)

Currently, this will result in the following being rendered in the PDF:
<img width="492" alt="Screenshot 2022-06-01 at 13 32 15" src="https://user-images.githubusercontent.com/32269665/171405134-be6f64e0-099c-49da-8146-754732861477.png">

Working around this limitation appears to be quite challenging. Obviously any custom `code` renderer will not be hit.

**Comment by danomatic** [comment]
this can probably just duplicate the behavior for `pre`. I'll look into it

**Comment by danomatic** [comment]
I think this is already supported

**Comment by JorgeAtPaladin** [comment]
Hey I have the same issue, how was this resolved? @danomatic 

It looks like your <pre> tag considers the child as raw text even though that's not up to HTML spec, instead <pre> should simply not ignore whitespace and newlines etc.

![Capture d’écran 2024-05-02 à 11 40 16](https://github.com/danomatic/react-pdf-html/assets/87263486/3cae02de-6bde-42e3-95cf-108de525a47d)
