### ISSUE TITLE
 not render bold, italic, super script and sub script... 

### ISSUE THREAD

**Issue by mahamedh** [danomatic/react-pdf-html#32]
`const element2 = (
  <html>
    <body>
      <style>
        {`
        .heading4 {
          background: darkgreen;
          color: white;
        }
        pre {
          background-color: #eee;
          padding: 10px;
        }`}
      </style>

      <h1>Heading 1</h1>
      <h2 style={{ backgroundColor: 'pink' }}>Heading 2</h2>
      <div>&nbsp;<strong>Bold</strong></div>
      <div><em>Italian</em></div>
     <div><strong><em>Italian</em></strong>
     <div><strong>X<sup>2</sup>as&nbsp; w<sub>sea</sub>aer</strong></div></div> 
    </body>
  </html>

![image](https://user-images.githubusercontent.com/44221394/172826841-d6974dae-bddc-46ab-9e07-754c3a4ee42d.png)

@danomatic @pmelab @Leksat

**Comment by TimHav** [comment]
@mahamedh bold and italic are working, but you need to include a font that has a bold and italic variant.
For example:

```js
  Font.register({
    family: "Roboto",
    fonts: [
      {
        src: "/fonts/Roboto-Regular.ttf",
      },
      {
        src: "/fonts/Roboto-Bold.ttf",
        fontWeight: "bold",
      },
      {
        src: "/fonts/Roboto-Italic.ttf",
        fontStyle: "italic",
      },
    ],
  });
```

See also https://react-pdf.org/fonts

**Comment by danomatic** [comment]
Closing because this seems to be an issue with loading the correct fonts
