### ISSUE TITLE
Font size not working?

### ISSUE THREAD

**Issue by aaronduce** [danomatic/react-pdf-html#33]
fontSize doesn't seem to be working? 

```js
...

    const PDFhtml = ReactDOMServer.renderToStaticMarkup(
        <html>
            <body>
                <p style={{fontFamily: 'IBMPlexSans', fontSize: 48}}>15855</p>
            </body>
        </html>
    );


    const PDFDocument = () => (
        <Document title="Title">
            <Page
                size="A4"
            >
                <Html>
                    {PDFhtml.toString()}
                </Html>
            </Page>
        </Document>
    )

...
```

Renders to:
```html
<html><body><p style="font-family:IBMPlexSans;font-size:48px">15855</p></body></html>
```

Now, as far as I can tell from the docs px is not supported unit for react-pdf, so this is possibly the cause? Although I have tried passing a string through the html style, '36pt', which should be supported and rendering the following:

```html
<html><body><p style="font-family:IBMPlexSans;font-size:36pt">15855</p></body></html>
```

But this doesn't work either. The font size in the document stays base.

**Comment by sanchitos** [comment]
Font family are not working according to https://github.com/danomatic/react-pdf-html/issues/27

On the other hand I think these libraries only support pixels as unit. Change 36pt to 36px.

**Comment by danomatic** [comment]
@sanchitos font-family works for me, but there seems to be confusion or a problem with font-family not working if combining italic, bold etc.
