### ISSUE TITLE
fontweight and style is not working

### ISSUE THREAD

**Issue by jobingn** [danomatic/react-pdf-html#39]
Bold and italics is not supported

**Comment by pwnedev** [comment]
Got the same problem, font-style and font-weight don't work. Neither <em> <i> <strong> <b> tags.

**Comment by zbiggs1** [comment]
Same

**Comment by pavodev** [comment]
Same here ✌🏼

**Comment by danomatic** [comment]
@jobingn, @pwnedev, @zbiggs1 and @pavodev please verify that you loaded the fonts correctly and provide a code example

**Comment by pwnedev** [comment]
> @jobingn, @pwnedev, @zbiggs1 and @pavodev please verify that you loaded the fonts correctly and provide a code example

Sorry for taking so long to reply, only now I got some time to work on the issue.

It looks like there isn't any bug, had to use Font.register to register my font to be used on the PDF Doc.

**Comment by pavodev** [comment]
Hi @Blake254,

There you go:
`
// FONTS

import PoppinsLight from '../../fonts/poppins-latin/poppins-v20-latin-300.ttf';
import PoppinsRegular from '../../fonts/poppins-latin/poppins-v20-latin-regular.ttf';
import PoppinsSemiBold from '../../fonts/poppins-latin/poppins-v20-latin-500.ttf';
import PoppinsBold from '../../fonts/poppins-latin/poppins-v20-latin-600.ttf';
import PoppinsExtraBold from '../../fonts/poppins-latin/poppins-v20-latin-700.ttf';

Font.register({
  family: 'PoppinsLight',
  fonts: [{ src: PoppinsLight }],
});

Font.register({
  family: 'PoppinsRegular',
  fonts: [{ src: PoppinsRegular }],
});

Font.register({
  family: 'PoppinsSemiBold',
  fonts: [{ src: PoppinsSemiBold }],
});

Font.register({
  family: 'PoppinsBold',
  fonts: [{ src: PoppinsBold }],
});

Font.register({
  family: 'PoppinsExtraBold',
  fonts: [{ src: PoppinsExtraBold }],
});

`
