### ISSUE TITLE
Link Tag

### ISSUE THREAD

**Issue by avneet2112** [danomatic/react-pdf-html#40]
Hii,
This is to update you that I am using this library in react-pdf/@renderer. And in the recent updates, they did the changes regarding the Link tag, previously they are simply working with:
`<Link src={link}>This is a link</Link>`
But now they are doing like this
`<Link src={link}><Text>This is a link</Text></Link>`

But when I used this library and embed anchor tag then it is showing this error
![Screenshot (2)](https://user-images.githubusercontent.com/86337608/191894891-2b2f8b46-d12a-41ee-997f-8e770d809403.png)
due to which the anchor tag is not visible in the pdf. 
So can you please update this library as soon as possible so these links will work on my side also.

**Comment by greatelv** [comment]
same issue.

**Comment by drewscott16** [comment]
Same issue as well, had to revert to previous version of react-pdf-renderer.

**Comment by avneet2112** [comment]
> Same issue as well, had to revert to previous version of react-pdf-renderer.

If we do so then we may lose the feature of the bookmark which is very crucial in the pdf.

**Comment by drewscott16** [comment]
> 

Yea I wouldn't recommend this or say this is the solution but for us it was the best alternative until this is fixed, which is hopefully soon.  I would imagine this is a pretty easy fix.

**Comment by danomatic** [comment]
This should be fixed in the latest version: https://github.com/danomatic/react-pdf-html/releases/tag/v1.1.12

Commit: https://github.com/danomatic/react-pdf-html/commit/53dddb186ed9b9145a6771a70e8ac31b53068b4d

**Comment by avneet2112** [comment]
Thank you:)
