### ISSUE TITLE
Cannot read property debug of undefined in @react-pdf renderer primitives 

### ISSUE THREAD

**Issue by brano93** [danomatic/react-pdf-html#43]
This issue is happening only in 1.1.13 and 1.1.14 version.

When I try to generate pdf I'm getting following error:
`TypeError: Cannot read properties of undefined (reading 'debug')`

I think it has something to do with this PR on react-pdf:
`There is outstanding issue with regards to https://github.com/diegomura/react-pdf/pull/1864/files.`

**Comment by danomatic** [comment]
@brano93 do you have the latest version of react-pdf?
