### ISSUE TITLE
Include source maps in the package to avoid "Failed to parse source map" warnings

### ISSUE THREAD

**Issue by rgembalik** [danomatic/react-pdf-html#45]
Is there any chance of including source maps in the package that's published on npm?

When using with CRA, I get the below warnings all the time and sometimes they obfuscate the actual errors from the app while debugging:

```
WARNING in ./node_modules/react-pdf-html/dist/tags.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'path/to/project/node_modules/react-pdf-html/dist/tags.js.map' file: Error: ENOENT: no such file or directory, open 'path/to/project/node_modules/react-pdf-html/dist/tags.js.map'

**Comment by danomatic** [comment]
I'll look into this

**Comment by danomatic** [comment]
@rgembalik, maps were building but were ignored from the npm publish. that latest version, `v1.1.17` has them

**Comment by rgembalik** [comment]
@danomatic Sorry for bugging you again, but I checked the compilation and while the source map files are there, the compilation still contains warnings, although a bit different.

I investigated it a bit and (if I understand correctly), the package needs its source files to be included OR the source needs to be included in the maps `sourcesContent` field. The latter is true for the react project I am working with, but I don't know enough about sourcemaps to tell if that's the correct way of doing it. If so, it can be enabled with `compilerOptions -> inlineSources` set to `true`

https://github.com/danomatic/react-pdf-html/blob/2b680ecd2990ce538d780e8ef0b0f9c2eda6f279/tsconfig.json#L57

Below is the full text of the new warning:

```
WARNING in ./node_modules/react-pdf-html/dist/tags.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'path/to/project/node_modules/react-pdf-html/src/tags.ts' file: Error: ENOENT: no such file or directory, open 'path/to/project/node_modules/react-pdf-html/src/tags.ts'
 @ ./node_modules/react-pdf-html/dist/render.js 56:15-32
 @ ./node_modules/react-pdf-html/dist/index.js 29:15-34
 @ ./src/components/PDFGenerator/PDFGenerator.js 12:0-34 200:37-41
 @ ./src/pages/DocumentCallPage/DocumentCallPage.js 36:0-70 602:49-61
 @ ./src/index.js 18:0-73 105:48-64

**Comment by walsh-super** [comment]
I'm seeing the same error
