### ISSUE TITLE
Italics and bold not working

### ISSUE THREAD

**Issue by simeondev15** [danomatic/react-pdf-html#48]
I have copied the exact same example content provided in the package, but italics and bold do not render in the pdf 
I am using @react-pdf/renderer. All other html elements like underline, lists, tables,etc work except bold and italics.

Sample html:
`<p><em>asfsdfsd</em></p><ul><li><b><u>sadad</u></b></li><li>asdad</li><li>adasd</li></ul><ol><li>asdasd</li><li>asdada</li></ol><p><br></p>`

[https://i.imgur.com/MIDDwMK.png](url)

**Comment by robyhuzwandar** [comment]
Hi, you should define the fontFamily

**Comment by danomatic** [comment]
Closing for now. @simeondev15 if you are defining the font family properly and still have issues, please provide a more complete sample for reproducing your issue.

**Comment by manoharreddyporeddy** [comment]
Yes, its not working, even after registering fonts

A
To make it work, do as below:

1
Registered 3 fonts
( normal, bold, italic )
from 3 files

with same name `Roboto`

2
we changed html
from 
```
  <b> something bold </b>
  <i> something italic </i>
```
to
```
    <span style="font-family:Roboto; font-weight: bold;"> something bold </span>
    <span style="font-family:Roboto; font-style: italic;"> something italic </span>
```

B
Without above html change
If its working properly for you
please provide your sample complete code here
it will help others.
