### ISSUE TITLE
Error: Failed to parse source map 

### ISSUE THREAD

**Issue by walsh-super** [danomatic/react-pdf-html#52]
Hi! Great package. I'm noticing constant error logging. I see this was previously closed, but I wanted to re-open. 

Referencing previous comment:
 
             @danomatic Sorry for bugging you again, but I checked the compilation and while the source map files are there, the compilation still contains warnings, although a bit different.

I investigated it a bit and (if I understand correctly), the package needs its source files to be included OR the source needs to be included in the maps `sourcesContent` field. The latter is true for the react project I am working with, but I don't know enough about sourcemaps to tell if that's the correct way of doing it. If so, it can be enabled with `compilerOptions -> inlineSources` set to `true`

https://github.com/danomatic/react-pdf-html/blob/2b680ecd2990ce538d780e8ef0b0f9c2eda6f279/tsconfig.json#L57

Below is the full text of the new warning:

```
WARNING in ./node_modules/react-pdf-html/dist/tags.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'path/to/project/node_modules/react-pdf-html/src/tags.ts' file: Error: ENOENT: no such file or directory, open 'path/to/project/node_modules/react-pdf-html/src/tags.ts'
 @ ./node_modules/react-pdf-html/dist/render.js 56:15-32
 @ ./node_modules/react-pdf-html/dist/index.js 29:15-34
 @ ./src/components/PDFGenerator/PDFGenerator.js 12:0-34 200:37-41
 @ ./src/pages/DocumentCallPage/DocumentCallPage.js 36:0-70 602:49-61
 @ ./src/index.js 18:0-73 105:48-64

_Originally posted by @rgembalik in https://github.com/danomatic/react-pdf-html/issues/45#issuecomment-1383601132_

**Comment by danomatic** [comment]
@walsh-super I set `inlineSources ` to `true` and published. Let me know if that's working better for you!
