### ISSUE TITLE
Does it have svg support?

### ISSUE THREAD

**Issue by aykutyilmaz37** [danomatic/react-pdf-html#56]
I must add svg include html,but it doesnt work. Any suggestions?

**Comment by danomatic** [comment]
Oh interesting. That hasn’t come up yet. If react-pdf supports it it should be possible, though it may not support ever feature that a browser will.

**Comment by danomatic** [comment]
@aykutyilmaz37 it should support inline svgs now thanks to https://github.com/danomatic/react-pdf-html/pull/77
