### ISSUE TITLE
<strong> and <b> tags do no bold text in <Html> component.

### ISSUE THREAD

**Issue by starfiresd** [danomatic/react-pdf-html#62]
Is there a trick to getting bold to work? I even tried doing a custom class .bold-text that has font-weight bold and 700. The fontFamily: 'Times-Bold' works for my <Text /> component, but when I pass an html string with the <b></b> or <strong></strong> tag into the <Html /> component, it doesn't bold the text. I tried to register Fonts but it didn't work or I didn't do it correctly.

`import { StyleSheet, Font } from '@react-pdf/renderer';

Font.register({
  family: 'Roboto',
  fonts: [
    {
      src: `/Roboto-Regular.ttf`,
    },
    {
      src: `/Roboto-Bold.ttf`,
      fontWeight: 'bold',
    },
    {
      src: `/Roboto-Italic.ttf`,
      fontWeight: 'normal',
      fontStyle: 'italic',
    },
    {
      src: `/Roboto-BoldItalic.ttf`,
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
  ],
});

const pdfStyles = StyleSheet.create({
  cover: {
    page: {
      backgroundColor: '#3D1E5A',
      marginTop: 15,
      marginHorizontal: 15,
    },
    title: {
      color: 'white',
      fontSize: 72,
      textAlign: 'center',
      fontFamily: 'Times-Roman',
      marginTop: 15,
    },
    subtitle: {
      color: 'white',
      fontSize: 28,
      textAlign: 'center',
      fontFamily: 'Times-Roman',
      marginBottom: 15,
    },
    notice: {
      backgroundColor: 'white',
      marginHorizontal: '12%',
      marginBottom: 15,
      height: '35%',
    },
    project: {
      backgroundColor: '#DDE4FF',
      height: '100%',
      marginHorizontal: '0.5%',
      marginBottom: '0.5%',
      marginTop: 12,
    },
    content: {
      backgroundColor: 'white',
      marginHorizontal: '12%',
      height: '23%',
    },
    text: {
      fontSize: 12,
      textAlign: 'center',
      fontFamily: 'Times-Roman',
      marginHorizontal: 12,
      marginTop: 12,
    },
  },
  page: {
    border: 1,
    borderStyle: 'solid',
    height: '96%',
    marginHorizontal: '2%',
    paddingHorizontal: 10,
  },
  pageMarker: {
    fontSize: 9,
    textAlign: 'center',
    margin: 2,
  },
  metadata: {
    fontSize: 10,
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 5,
    fontFamily: 'Times-Bold',
  },
  html: {
    fontSize: 12,
    textAlign: 'justify',
    margin: 10,
    border: 1,
    borderStyle: 'solid',
    padding: 10,
    fontFamily: 'Roboto',
  },
});

export default pdfStyles;
`

`import React from 'react';
import { Page, View, Text } from '@react-pdf/renderer';
import Html from 'react-pdf-html';
import pdfStyles from './pdfstyles';

export default function PdfContent({ item }) {
        
    const pdfHtml = `
      <html>
        <style>
          body {
            font-size: 10px;
            text-align: justify;
            color: #000000;
          }
          h2 {
            margin: 0px;
            color: #000000;
          }
          h3 {
            margin: 0px;
            margin-bottom: 2px;
            color: #000000;
            text-decoration: underline;
          }
          p {
            margin: 1px;
          }
          ol {
            font-size: 10px;
            margin: 0px;
          }
          ul {
            font-size: 10px;
            margin: 0px;
          }
          li {
            font-size: 10px;
            margin: 0px;
          }
          span {
            margin: 0px;
          }
          .indent {
            margin-left: 5px;
          }
        </style>
        <body>
            <h2>PDF Print Test Record</h2>
            <br>
            <h3>Headerh3>
            <span class="indent<strong>Bold</strong>span>
        </body>
      </html>
      `;

      console.log(pdfHtml);
    return(
        <>
            <Page size='LETTER'>
                <Text style={pdfStyles.pageMarker} fixed>Marker</Text>
                <View style={pdfStyles.page} >
                    <Text style={pdfStyles.metadata}>{item.id} | {item.metadata.table} | {item.metadata.report}</Text>
                    <Html style={pdfStyles.html}>{pdfHtml}</Html>
                </View>
                <Text style={pdfStyles.pageMarker} fixed>Marker</Text>
            </Page>
        </>
    )
}

`

**Comment by Olovyannikov** [comment]
```
// fonts are in the public folder

Fonts.register({
  family: 'Roboto',
  fonts: [
    {
      src: '/fonts/Roboto-Bold.ttf',
      fontWeight: 'bold'
    }
  ]
})

const styles = {
  b: {
    fontFamily: 'Roboto';
    fontWeight: 'bold';
  }
}

const html = '<div><ul><li><b>This is a bold text</b></li></ul></div>'

export const HtmlToPdf = () => {
  <Document>
    <View>
      <Html stylesheet={styles}>{html}</Html>
    </View>
  </Document>
}
```

This works for me

**Comment by starfiresd** [comment]
@Olovyannikov I'm still fairly new. I have entered the code you did, but don't see any fonts in the public folder. I assume I need to add those somewhere?

**Comment by heijmerikx** [comment]
My 2 cents after struggling for quite some time to get bold to work with the default font family. I didn't get it to work either. Both using the inline stylesheet nor with the optional stylesheet property. (Not for style properties, <b> nor <strong>)

**Comment by AlpineM** [comment]
I have this issue too, furstrated by the lack of support for basic HTML elements such as <strong> and <em>.

**Comment by AlpineM** [comment]
I was able to make `<strong>` and `<em>` work individually by changing their font in the react-pdf stylesheet:

`const styles = StyleSheet.create({
  strong: {
    fontFamily: 'Helvetica-Bold',
  },
  em: {
    fontFamily: 'Helvetica-Oblique',
  },
});`

However this solution is clunky, and it's impossible to have a piece of text be both bold and italicized at the same time.

**Comment by danomatic** [comment]
I believe this is a limitation with `react-pdf`/PDF files. It's finicky with how bold, italic, etc are applied in that you have to have to supply a font for each combination:

```ts
Font.register({
  family: 'OpenSans',
  fonts: [
    { src: fonts + '/Open_Sans/OpenSans-Regular.ttf' },
    { src: fonts + '/Open_Sans/OpenSans-Bold.ttf', fontWeight: 'bold' },
    { src: fonts + '/Open_Sans/OpenSans-Italic.ttf', fontStyle: 'italic' },
    {
      src: fonts + '/Open_Sans/OpenSans-BoldItalic.ttf',
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
  ],
});
```

**Comment by JorgeAtPaladin** [comment]
@danomatic for us it all works fine as long as the whole string is marked as bold but as soon as we render a portion of the string as bold eg. Hello, <b>world</b> it all becomes non bold?

**Comment by romulo20** [comment]
@JorgeAtPaladin  , I experienced the same problem and found a workaround by following what the last comment did here. [https://github.com/danomatic/react-pdf-html/issues/90](react-pdf-html/issues/90)

 Overriding the @react-pdf/layout to version 3.11.5 in package.json
 
```
 "overrides": {
    "@react-pdf/layout": "3.11.5"
},
```
