### ISSUE TITLE
suggestion:  css-tree instead of css

### ISSUE THREAD

**Issue by mikey0000** [danomatic/react-pdf-html#7]
css is basically abandoned

css-tree offers similar functionality and behaviours. I had a go at replacing but my domain knowledge of css nodes is a bit limited.
It looks a lot more powerful for finding specific node types without having to do if checks everywhere.

@danomatic I think you might be able to swap them over faster than me but if you don't get around to it I might try.

**Comment by danomatic** [comment]
@mikey0000 this is done in the latest version `v1.1.2`
