### ISSUE TITLE
Error not found module jpeg-exif/lib

### ISSUE THREAD

**Issue by vuthanhtung172906** [danomatic/react-pdf-html#72]
ERROR in ./node_modules/jpeg-exif/lib/index.js 
Module not found: Error: Can't resolve 'fs' in '/Users/my_project/node_modules/jpeg-exif/lib'

ERROR in ./node_modules/react-pdf-html/dist/resolveCssFile.js 
Module not found: Error: Can't resolve 'fs' in '/Users/my_project/node_modules/react-pdf-html/dist'

ERROR in ./node_modules/react-pdf-html/dist/resolveCssFile.js 
Module not found: Error: Can't resolve 'url' in '/Users/my_project/node_modules/react-pdf-html/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

ERROR in ./node_modules/react-pdf-html/dist/resolveCssFile.js 
Module not found: Error: Can't resolve 'path' in '/Users/my_project/node_modules/react-pdf-html/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

Notes: This error dont exist after i update new version of react-pdf-html

**Comment by danomatic** [comment]
@vuthanhtung172906 this seems to be a module loader issue with the newest `react-pdf`, unrelated to this library.

**Comment by danomatic** [comment]
@vuthanhtung172906 it also seem that you are having this issue because you are running `react-pdf-html` in a browser. I haven't tried this yet as my purpose was to run it in node on a server. Perhaps there is a way to add support for both browser and server but right now the new version is written to support loading local external CSS files. Input/PRs welcome.

**Comment by Demiurge1979** [comment]
@vuthanhtung172906  

have you tried this: 

https://stackoverflow.com/questions/70591567/module-not-found-error-cant-resolve-fs-in-react

The answer of Nick (first after the green check) helps me on today. I know it is a workarround and i have to check the rest of my browser app, but perhaps it helps you.

**Comment by bakhtiarmochamad** [comment]
@Demiurge1979 if use nextjs, it's solution can relate?

**Comment by Demiurge1979** [comment]
I am using react TS and here it works. I only replied because I received a similar message.

**Comment by bakhtiarmochamad** [comment]
"resolutions": {
    "react-pdf-html": "1.1.10",
    "@react-pdf/renderer": "3.0.0",
    "@react-pdf/pdfkit" : "3.0.0",
    "@react-pdf/image":"2.2.0",
    "@react-pdf/layout":"3.2.1"
  }

i have add this in package.json and my application work again

**Comment by absogod** [comment]
> "resolutions": { "react-pdf-html": "1.1.10", "@react-pdf/renderer": "3.0.0", "@react-pdf/pdfkit" : "3.0.0", "@react-pdf/image":"2.2.0", "@react-pdf/layout":"3.2.1" }
> 
> i have add this in package.json and my application work again

still doesn't work.

**Comment by danomatic** [comment]
I removed those imports in `v2.0.0`
