### ISSUE TITLE
Uncaught TypeError: renderer_1.StyleSheet is undefined

### ISSUE THREAD

**Issue by Demiurge1979** [danomatic/react-pdf-html#73]
Hello, 

we got an Exception "Uncaught TypeError: renderer_1.StyleSheet is undefined" with the latest Versions. We have no idea, what was changed. 

![error](https://github.com/danomatic/react-pdf-html/assets/91942124/8b4d359e-1a48-4094-9415-0322d2b9b219)

We also try an new empty project with the example coe from this page and got the same problem. 

Can anybody help?

thanx
Bjoern

**Comment by danomatic** [comment]
Hi @Demiurge1979, this looks like a module loader issue. None of that has changed version to version. Do you not have the error with the previous version?

**Comment by danomatic** [comment]
@Demiurge1979 is this fixed for you with the latest version `v1.3.7`?

**Comment by Demiurge1979** [comment]
@danomatic i will test it by the end of next week. On tuesday we have a big realease and i need all my concentration for this action.

**Comment by danomatic** [comment]
Sounds good. Please also check out `v2.0.2`

**Comment by danomatic** [comment]
@Demiurge1979 I'm closing this but please ping if you're still having trouble.
