### ISSUE TITLE
Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by tbrandle** [danomatic/react-pdf-html#78]
I'm running into an error in the browser complaining about the `StyleSheet.create` method in `createHtmlStylesheet`. 

Here are my versions:
```
    "@react-pdf/renderer": "^3.1.17",
    "@types/react": "^18.2.55",
    "react-pdf-html": "1.1.22",
```

Any help would be appreciated!

**Comment by jpblopez** [comment]
Im having the same problem here. I tried editing the code inside the package itself but no luck. My versions:


```
node -v
v16.18.1
```

package.json

```
    "@react-pdf/renderer": "^3.3.8",
    "react": "^18.2.0",
    "react-pdf-html": "^1.2.0"
```

**Comment by mikolajmigacz** [comment]
Hi!

I encountered the same issue, and I was able to solve it by downgrading `@react-pdf/renderer` to version `3.1.14` and `react-pdf-html` to `1.1.22`.

**Comment by danomatic** [comment]
Has anyone found a root cause for this? the @react-pdf/renderer docs still seem to reference `StyleSheet.create`: https://react-pdf.org/styling

**Comment by danomatic** [comment]
I'm going to consider this closed and a react-pdf issue until I hear otherwise
