### ISSUE TITLE
Images are showing while downloading or view in other browser

### ISSUE THREAD

**Issue by dhwaj1902** [danomatic/react-pdf-html#79]
Images are not showing while downloading the PDF or in any other browser except chrome.
I have changed how the images rendered in `react-pdf-html` with this:

<img width="840" alt="image" src="https://github.com/danomatic/react-pdf-html/assets/57860123/6ff3c7ed-74db-40e1-b37a-7e462c0dac95">

Images with Image Urls are now showing perfectly fine only in chrome not in other browsers (not even while download the pdf using the chrome).

Used the S3 URLs for Images.

**Comment by fendermany** [comment]
Same problem with firebase. Just fix it by 
<img width="892" alt="image" src="https://github.com/danomatic/react-pdf-html/assets/71121334/8151f744-05d8-4e24-9140-6ebb899591e8">

**Comment by danomatic** [comment]
Latest code has `'Access-Control-Allow-Origin': '*'`
