### ISSUE TITLE
Undefined Stylesheet Error after upgrading to react 18.2

### ISSUE THREAD

**Issue by vertual-hb** [danomatic/react-pdf-html#82]
Hi,

This is very similar to issue #73 (unresolved)

I upgraded to react 18.2 from 17.0.2 and upgraded react-pdf-html to 1.2.1 from 1.1.18.
React scripts is 5.0.1 in both cases.
There was an error initially `Module not found: Error: Can't resolve fs in ...\node_modules\react-pdf-html\dist`.
I disabled `fs` in `croco.config.js` with `resolve: { fallback: { fs: false } }` . The project then builds without issues. 
When I called pdf(data) using` import pdf @react-pdf/renderer` afterwards, I get the following error message on console.
data includes '\<Html stylesheet={customStyles} style={customStyles.html}\>{html.replace(...)}\</Html\>'.
 Used import {Html} from 'react-pdf-html';
```
react-reconciler.production.min.js:106 TypeError: Cannot read properties of undefined (reading 'create')
    at t.createHtmlStylesheet (styles.ts:180:21)
    at t.default (render.tsx:349:22)
    at t.default (Html.tsx:15:13)
    at Tn (react-reconciler.production.min.js:64:98)
    at $r (react-reconciler.production.min.js:160:456)
    at $i (react-reconciler.production.min.js:139:22)
    at Ji (react-reconciler.production.min.js:138:366)
    at qi (react-reconciler.production.min.js:132:214)
    at react-reconciler.production.min.js:30:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:438)
```

The same code runs without issues with react 17.0.2 with no fs fallback required.

Thank you

**Comment by danomatic** [comment]
I'm not sure how to support `fs` in a browser. I know that `@react-pdf/renderer` does it somehow but I'm not sure the exact method.

**Comment by danomatic** [comment]
I removed fs in `v2.0.0`

**Comment by vertual-hb** [comment]
Thanks,
 It is working now
