### ISSUE TITLE
cannot import react-pdf-html v1.3.2 in plain esm project

### ISSUE THREAD

**Issue by anajavi** [danomatic/react-pdf-html#83]
The package.json points to directory mjs, which does not exist:
https://github.com/danomatic/react-pdf-html/blob/7799a3f3b4bf91c17ac8bf2c48269a999e4619cf/package.json#L23

fixing that to point to "./dist/esm/index.js" causes another problem:
```
 Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/proj/node_modules/react-pdf-html/dist/esm/Html'
```
I guess it is caused by missing .js extensions in dist/esm/index.js:
```js
export { default, default as Html } from './Html';
```

**Comment by yaredtsy** [comment]
its also happening to me since today.
```
  ✘ [ERROR] Failed to resolve entry for package "react-pdf-html". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
  ```

**Comment by danomatic** [comment]
We just added support for ES modules. Please try `v1.3.3`

**Comment by anajavi** [comment]
The v1.3.3 fixed the import directory, but node still complains about missing file extension. I guess that the .js extensions should be added to the source code. [Typescript does not seem to have an option to add those extensions.](https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937)

test.mjs contains only the import:
```js
import html from 'react-pdf-html';
```

output:
```sh
$ node test.mjs
node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/proj/node_modules/react-pdf-html/dist/esm/Html' imported from /proj/node_modules/react-pdf-html/dist/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///proj/node_modules/react-pdf-html/dist/esm/Html'
}

Node.js v20.11.0
```

**Comment by danomatic** [comment]
Ok try `v1.3.4`

**Comment by danomatic** [comment]
Hmm ok. I'm not sure how to handle 3rd party libraries being CommonJS, but I just updated all the dependences and published `v.1.3.5`. Try that!

**Comment by danomatic** [comment]
I just published a new version `v1.3.6` that does not require `esModuleInterop`

**Comment by anajavi** [comment]
v1.3.7 works fine. Thank you!

**Comment by anajavi** [comment]
> Hmm...but I am getting this when I bundle it with esbuild:

I am not familiar with esbuild, but maybe requiring sync-fetch would work?

```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const fetch = require('sync-fetch');
```

**Comment by danomatic** [comment]
I decided not to support local external stylesheets and fs in `v2.0.0`
