### ISSUE TITLE
Can't style a list

### ISSUE THREAD

**Issue by hotcakedev628** [danomatic/react-pdf-html#9]
I was trying to remove list style type, but not able to do it.

In front of a `<li></li>` tag, there were two dots.
![image](https://user-images.githubusercontent.com/60177750/129748140-38c98227-547c-4e73-acd3-8324e0c9276e.png)

How to remove a dot?

I tried this.

```
const stylesheet = Stylesheet.create({
  ul: {
    listStyleType: 'none'
  }
});

<Html style={stylesheet}>{html}</Html>
```

It didn't work for me.

**Comment by danomatic** [comment]
Hi @hotcakedev628, can you provide a more complete example of the html that you are trying to render? Specifically I want to see the html for the entire `<ol>` or `<ul>` element that has the `<li>` that is giving you trouble.

**Comment by hotcakedev628** [comment]
Hi @danomatic 
Happy to hear from you.

Technically, I am getting the html content from a database which was saved using [Quill](https://quilljs.com) editor in React.js.

So it looks like a normal text.
```
const html = "<ul><li>First</li><li>Second</li></ul>";

<Html style={stylesheet}>{html}</Html>
```

In general, I can remove the unnecessary dots by adding style `listStyleType: 'none'` to `ul` element when I rendered the html content using [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

But not able to remove them in `@react-pdf/renderer` and `react-pdf-html`.

**Comment by danomatic** [comment]
I wasn't able to reproduce the specific issue. For me a simple list like `<ul><li>First</li><li>Second</li></ul>` renders only with single bullets.

But I did just do a new release `v1.1.0` that adds support `listStyleType: 'none'` or `listStyle: 'none'`. Please give it a try and let me know what you think!

**Comment by hotcakedev628** [comment]
Hi @danomatic Thanks. The new version worked for me.

After checking the database with our back-end guy, I noticed there already were dots inside `li` tag.

It was looking like...
```
<ul><li>•	First</li><li>•	Second</li></ul>
```

It would be helpful for other developers who use `quill.js` like me.

Thank you.
